NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src

include $(AM_HOME)/Makefile

# SRCS     = src/riscv/nemu/start.S \
#            src/riscv/nemu/cte.c \
#            src/riscv/nemu/trap.S \
#            src/riscv/nemu/vme.c
#            src/platform/nemu/trm.c \
#            src/platform/nemu/ioe/ioe.c \
#            src/platform/nemu/ioe/timer.c \
#            src/platform/nemu/ioe/input.c \
#            src/platform/nemu/ioe/gpu.c \
#            src/platform/nemu/ioe/audio.c \
#            src/platform/nemu/ioe/disk.c \
#            src/platform/nemu/mpe.c

# AM_SRCS  = riscv/nemu/start.S \
#            riscv/nemu/cte.c \
#            riscv/nemu/trap.S \
#            riscv/nemu/vme.c
# AM_SRCS := platform/nemu/trm.c \
#            platform/nemu/ioe/ioe.c \
#            platform/nemu/ioe/timer.c \
#            platform/nemu/ioe/input.c \
#            platform/nemu/ioe/gpu.c \
#            platform/nemu/ioe/audio.c \
#            platform/nemu/ioe/disk.c \
#            platform/nemu/mpe.c
